package com.myspace.quotemanagedrules;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement   (name="quote")
public class QuoteDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private String id;

	@org.kie.api.definition.type.Label("Version")
	private String version;

	@org.kie.api.definition.type.Label("AccountId")
	private String accountId;

	@org.kie.api.definition.type.Label("Revision")
	private Integer revision;

	@org.kie.api.definition.type.Label("Price")
	private Integer price;

	@org.kie.api.definition.type.Label("CorrelationId")
	private java.lang.String correlationId;

	@org.kie.api.definition.type.Label("OppurtunityId")
	private java.lang.String oppurtunityId;

	@org.kie.api.definition.type.Label("oppurtunityName")
	private java.lang.String oppurtunityName;

	public QuoteDto() {
	}

	@Override
	
	public String toString() {
		return "Price in ToString is  : " + price;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public java.lang.String getCorrelationId() {
		return this.correlationId;
	}

	public void setCorrelationId(java.lang.String correlationId) {
		this.correlationId = correlationId;
	}

	public java.lang.String getOppurtunityId() {
		return this.oppurtunityId;
	}

	public void setOppurtunityId(java.lang.String oppurtunityId) {
		this.oppurtunityId = oppurtunityId;
	}

	public java.lang.String getOppurtunityName() {
		return this.oppurtunityName;
	}

	public void setOppurtunityName(java.lang.String oppurtunityName) {
		this.oppurtunityName = oppurtunityName;
	}

	public java.lang.Integer getRevision() {
		return this.revision;
	}

	public void setRevision(java.lang.Integer revision) {
		this.revision = revision;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public java.lang.String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(java.lang.String accountId) {
		this.accountId = accountId;
	}

	public QuoteDto(java.lang.String id, java.lang.String version,
			java.lang.String accountId, java.lang.Integer revision,
			java.lang.Integer price, java.lang.String correlationId,
			java.lang.String oppurtunityId, java.lang.String oppurtunityName) {
		this.id = id;
		this.version = version;
		this.accountId = accountId;
		this.revision = revision;
		this.price = price;
		this.correlationId = correlationId;
		this.oppurtunityId = oppurtunityId;
		this.oppurtunityName = oppurtunityName;
	}

}